version: '2'

services:
    server:
        image: anubarak_server
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - 10001:10001
        volumes:
            - ../data:/var/anubarak
